# Config file for automatic testing at travis-ci.org

language: python

matrix:
  include:
    - python: 3.8
      env: TOXENV=flake8
    - python: 3.5
      env: TOXENV=py35
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      env: TOXENV=py37
    - python: 3.8
      env: TOXENV=py38
    - python: 3.9-dev
      env: TOXENV=py39

install: pip install -U wheel tox codecov

cache: pip

# command to run tests, e.g. python setup.py test
script: tox

addons:
  apt:
    packages:
      - language-pack-fr

after_success:
    - codecov

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: scrapinghub
  password:
    secure: "Vs2Z69YTFzQWVkos7IvP4xk0RAQ35dzVXP+EAmzMkqi9qToTa7jdeF8deY18r3l8093jaJ/ct6NzjNiZ6ryWl1yKBwYoW+jaXjKGVXMFSQdqXiDreu516rqrOiRfZVHy+G9TabjhVrIW2npkxuOP7d0HONOZnNtCn6QrxQwEBzw="
  on:
    tags: true
    repo: scrapinghub/dateparser
    condition: "$TOXENV == py27"
